import {fenceOfficialDocument,fenceContentSecurityPolicy} from './account-storage-fence.mjs';
import {randomBytes} from 'node:crypto';
import {gunzipSync,brotliDecompressSync,inflateSync} from 'node:zlib';
import {writeFile,chown,rename,readFile} from 'node:fs/promises';
import {createServer,request as httpRequest} from 'node:http';
import {request as httpsRequest} from 'node:https';
const backend=new URL(process.env.WORKDSH_ADMIN_URL);
const origin=new URL(process.env.WORKDSH_USER_ORIGIN);
const adminOrigin=new URL(process.env.WORKDSH_ADMIN_WEB_ORIGIN);
if(backend.protocol!=='https:'||[backend,origin,adminOrigin].some(u=>u.pathname!=='/'||u.search||u.hash||u.username||u.password))throw Error('Fixed deployment origins required');
const cookieName='workdsh-member-session-'+(origin.port||'443');

const cookie=req=>{const entries=(req.headers.cookie??'').split(';').map(x=>x.trim()).filter(x=>x.startsWith(cookieName+'='));if(entries.length>1)throw Error('Ambiguous login');const token=entries[0]?.slice(cookieName.length+1);if(token&&!/^[A-Za-z0-9_-]{16,512}$/.test(token))throw Error('Invalid login');return token?'workdsh-admin-session='+token:'';};
const fail=(res,status)=>{res.writeHead(status,{'cache-control':'no-store'});res.end();};
function actor(req){return new Promise((resolve,reject)=>{const q=httpsRequest(new URL('/api/auth/me',backend),{headers:{cookie:cookie(req)}},r=>{let body='';r.on('data',b=>{body+=b;if(body.length>16000)q.destroy(Error('Oversized identity'));});r.on('end',()=>{if(r.statusCode!==200)return resolve();try{resolve(JSON.parse(body));}catch(e){reject(e);}});});q.on('error',reject);q.setTimeout(5000,()=>q.destroy(Error('Identity timeout')));q.end();});}
function bootstrap(user){return new Promise((resolve,reject)=>{const q=httpRequest({host:'127.0.0.1',port:user.port,path:'/?token='+user.token,headers:{host:origin.host}},r=>{user.runtimeCookies=(r.headers['set-cookie']??[]).map(x=>x.split(';')[0]).join('; ');r.resume();r.on('end',resolve);});q.on('error',reject);q.end();});}
export async function startGateway(users,lifecycle){

 const logins=new Map();const writes=new Map();
 const update=(u,fn)=>{const next=(writes.get(u.name)??Promise.resolve()).catch(()=>{}).then(async()=>{const current=logins.get(u.name);const pool=new Set(current);fn(pool);if(pool.size>64)throw Error('Member login registration limit');const file=u.root+'/login';await writeFile(file+'.next',JSON.stringify([...pool]),{mode:0o600});await chown(file+'.next',u.uid,u.gid??u.uid);await rename(file+'.next',file);logins.set(u.name,pool);});writes.set(u.name,next);return next;};
 const live=new Set();
 const revoke=key=>{for(const item of [...live])if(item.key===key)item.close();};
 const track=(req,user,close)=>{const key=cookie(req);const item={key,close:()=>{live.delete(item);close();},checking:false};live.add(item);const timer=setInterval(async()=>{if(item.checking)return;item.checking=true;try{const a=await actor(req);if(a?.id!==user.id||a?.organizationId!==user.org)item.close();}catch{item.close();}finally{item.checking=false;}},1000);timer.unref();const dispose=()=>{clearInterval(timer);live.delete(item);};return dispose;};
 const select=async req=>{const a=await actor(req);if(!a||a.mustChangePassword!==false)return;const user=await lifecycle.resolveMember(a);if(!logins.has(user.name)){let pool=[];try{pool=JSON.parse(await readFile(user.root+'/login','utf8'));}catch(e){if(e.code!=='ENOENT')throw e;}if(!Array.isArray(pool)||pool.some(x=>typeof x!=='string'))throw Error('Invalid login pool');logins.set(user.name,new Set(pool));}return user;};
 const enter=async(req,user)=>{await lifecycle.ensure(user,cookie(req));if(!user.runtimeCookies)await bootstrap(user);await update(user,pool=>pool.add(cookie(req)));};
 const header=(req,user)=>{const h={...req.headers,host:req.headers.host,cookie:user.runtimeCookies};for(const k of ['authorization','proxy-authorization','x-forwarded-host','x-forwarded-for','x-forwarded-proto'])delete h[k];return h;};
 const server=createServer(async(req,res)=>{try{
  if(!req.url?.startsWith('/')||req.url.startsWith('//'))return fail(res,400);const url=new URL(req.url,origin);if(url.searchParams.has('token'))return fail(res,403);if(req.headers.host!==origin.host||req.headers['sec-fetch-site']==='cross-site')return fail(res,403);if(!['GET','HEAD'].includes(req.method)&&req.headers.origin!==origin.origin)return fail(res,403);if(url.pathname.startsWith('/api/admin/')||url.pathname.startsWith('/api/internal/'))return fail(res,403);
  if(['/api/auth/browser-login','/api/auth/logout','/api/auth/me'].includes(url.pathname)){
   const q=httpsRequest(new URL(req.url,backend),{method:req.method,headers:{'content-type':req.headers['content-type']??'application/json',cookie:cookie(req),origin:adminOrigin.origin}},async r=>{try{if(url.pathname==='/api/auth/browser-login'&&r.statusCode===200){const backendCookie=(r.headers['set-cookie']??[]).map(x=>x.split(';')[0]).find(x=>x.startsWith('workdsh-admin-session='));if(backendCookie){const incoming={headers:{cookie:backendCookie.replace('workdsh-admin-session=',cookieName+'=')}};const u=await select(incoming);if(!u)throw Error('Member admission failed');await enter(incoming,u);}}if(url.pathname==='/api/auth/logout'&&r.statusCode>=200&&r.statusCode<300){revoke(cookie(req));for(const u of users){if(logins.get(u.name)?.has(cookie(req))){await update(u,pool=>pool.delete(cookie(req)));await lifecycle.logout(u,cookie(req));}}}const h={...r.headers};if(h['set-cookie'])h['set-cookie']=h['set-cookie'].map(x=>x.replace(/^workdsh-admin-session=/,cookieName+'=').replace(/Path=\/api(?=;|$)/i,'Path=/'));res.writeHead(r.statusCode,h);r.pipe(res);}catch{r.resume();if(!res.headersSent)fail(res,503);else res.destroy();}});q.on('error',()=>fail(res,502));req.pipe(q);return;
  }
  if(url.pathname==='/entry.js'){res.writeHead(200,{'content-type':'text/javascript;charset=utf-8','cache-control':'no-store'});res.end(await readFile('/server/shared-entry-client.js'));return;}
  if(url.pathname==='/login'||(url.pathname==='/'&&!cookie(req))){res.writeHead(200,{'content-type':'text/html;charset=utf-8','cache-control':'no-store'});res.end(await readFile('/server/user-entry.html'));return;}
  const user=await select(req);if(!user){if(req.method==='GET'&&['/','/workdsh/enter'].includes(url.pathname)){res.writeHead(303,{location:'/login','cache-control':'no-store'});res.end();return;}return fail(res,401);}await enter(req,user);if(url.pathname==='/workdsh/enter'){res.writeHead(303,{location:'/','cache-control':'no-store'});res.end();return;}
  if(url.pathname.startsWith('/__proof/'))return fail(res,404);
  const q=httpRequest({host:'127.0.0.1',port:user.port,path:req.url,method:req.method,headers:header(req,user)},r=>{const h={...r.headers};delete h['set-cookie'];if(url.pathname==='/'&&r.statusCode===200&&String(h['content-type']).includes('text/html')){const chunks=[];let bytes=0;r.on('data',b=>{bytes+=b.length;if(bytes>8*1024*1024){r.destroy();res.destroy();}else chunks.push(b);});r.on('end',()=>{try{const b=Buffer.concat(chunks);const enc=h['content-encoding'];const raw=enc==='gzip'?gunzipSync(b,{maxOutputLength:8*1024*1024}):enc==='br'?brotliDecompressSync(b,{maxOutputLength:8*1024*1024}):enc==='deflate'?inflateSync(b,{maxOutputLength:8*1024*1024}):b;const nonce=randomBytes(24).toString('base64url');const body=Buffer.from(fenceOfficialDocument(raw.toString(),{id:user.id,organizationId:user.org},nonce));delete h['content-encoding'];delete h.etag;h['content-length']=body.length;h['cache-control']='no-store';const csp=fenceContentSecurityPolicy(h['content-security-policy'],nonce);if(csp)h['content-security-policy']=csp;res.writeHead(200,h);res.end(body);}catch{fail(res,502);}});}else{res.writeHead(r.statusCode,h);r.pipe(res);}});const dispose=track(req,user,()=>{q.destroy();res.destroy();});res.once('close',dispose);q.on('error',()=>{dispose();if(!res.destroyed)fail(res,502);});req.pipe(q);
 }catch{fail(res,503);}});
 server.on('upgrade',async(req,socket,head)=>{try{if(!req.url?.startsWith('/')||req.url.startsWith('//')||new URL(req.url,origin).searchParams.has('token')||req.headers.host!==origin.host||req.headers.origin!==origin.origin){socket.destroy();return;}const user=await select(req);if(!user){socket.end('HTTP/1.1 401 Unauthorized\r\nConnection: close\r\n\r\n');return;}
 await enter(req,user);const q=httpRequest({host:'127.0.0.1',port:user.port,path:req.url,method:'GET',headers:header(req,user)});
 q.on('upgrade',(r,upstream,uphead)=>{socket.write('HTTP/1.1 '+r.statusCode+' '+r.statusMessage+'\r\n'+Object.entries(r.headers).filter(([k])=>k!=='set-cookie').map(([k,v])=>k+': '+v+'\r\n').join('')+'\r\n');if(uphead.length)socket.write(uphead);if(head.length)upstream.write(head);const dispose=track(req,user,()=>{socket.destroy();upstream.destroy();});socket.once('close',dispose);socket.pipe(upstream);upstream.pipe(socket);socket.on('error',()=>upstream.destroy());upstream.on('error',()=>socket.destroy());socket.on('close',()=>upstream.destroy());});q.on('response',()=>socket.destroy());q.on('error',()=>socket.destroy());q.end();
 }catch{socket.destroy();}});
 await new Promise((resolve,reject)=>{server.once('error',reject);server.listen(Number(process.env.WORKDSH_PORT||8080),'0.0.0.0',resolve);});
 return server;
}
