import test from 'node:test';
import assert from 'node:assert/strict';
import { spawn } from 'node:child_process';
import { once } from 'node:events';
import { MemberProcessSupervisor } from '../dist/process-supervisor.js';
const a={organizationId:'org',principalId:'a'},b={organizationId:'org',principalId:'b'};
function adapter(inspectIdle){const children=[];return {children,inspectIdle,async start(){const child=spawn(process.execPath,['-e',"setInterval(()=>process.stdout.write('work\\n'),20)"],{stdio:['ignore','pipe','ignore']});await once(child,'spawn');children.push(child);return {child,alive:()=>child.exitCode===null&&child.signalCode===null,async stop(){const exit=once(child,'exit');child.kill('SIGTERM');await exit;}};}};}
async function clean(x){for(const c of x.children){if(c.exitCode===null&&c.signalCode===null){const exit=once(c,'exit');c.kill();await exit;}}}
test('concurrent login reuses process; last logout preserves real background child by default',async()=>{const x=adapter(),s=new MemberProcessSupervisor(x);try{assert.equal(x.children.length,0);const [one,two]=await Promise.all([s.login(a,'one'),s.login(a,'two')]);assert.equal(one,two);assert.equal(x.children.length,1);const other=await s.login(b,'b');await s.logout(a,'one');assert.equal(await s.recycleIfIdle(a),'retained');await s.logout(a,'two');assert.equal(await s.recycleIfIdle(a),'retained');await once(one.child.stdout,'data');assert.ok(one.alive());assert.ok(other.alive());assert.equal(await s.login(a,'three'),one);}finally{await clean(x);}});
test('busy, unknown and failed quiescence checks never stop a process',async()=>{let state='busy';const x=adapter(async()=>{if(state==='error')throw Error('backend unavailable');return state;}),s=new MemberProcessSupervisor(x);try{const h=await s.login(a,'a');await s.logout(a,'a');for(state of ['busy','unknown','error']){assert.equal(await s.recycleIfIdle(a),'retained');assert.ok(h.alive());}}finally{await clean(x);}});
test('login arriving during idle probe cancels retirement',async()=>{let enter,release;const entered=new Promise(r=>enter=r),gate=new Promise(r=>release=r);const x=adapter(async()=>{enter();await gate;return 'idle';}),s=new MemberProcessSupervisor(x);try{const h=await s.login(a,'a');await s.logout(a,'a');const retire=s.recycleIfIdle(a);await entered;const login=s.login(a,'new');release();assert.equal(await retire,'retained');assert.equal(await login,h);assert.ok(h.alive());}finally{release?.();await clean(x);}});
test('only explicit exhaustive idle check permits stop and later restart',async()=>{const x=adapter(async()=> 'idle'),s=new MemberProcessSupervisor(x);try{const first=await s.login(a,'a');assert.equal(await s.recycleIfIdle(a),'retained');await s.logout(a,'a');assert.equal(await s.recycleIfIdle(a),'stopped');assert.ok(!first.alive());const second=await s.login(a,'new');assert.notEqual(second,first);assert.equal(x.children.length,2);}finally{await clean(x);}});
test('failed startup can retry; equal principal in different organizations cannot reuse',async()=>{let fail=true;const x=adapter(),s=new MemberProcessSupervisor({...x,async start(m){if(fail){fail=false;throw Error('failed');}return x.start(m);}});try{await assert.rejects(s.login(a,'a'));const first=await s.login(a,'retry'),second=await s.login({...a,organizationId:'other'},'other');assert.notEqual(first,second);}finally{await clean(x);}});

test('startup receives the queued login material, without a mutable latest-login slot',async()=>{const calls=[];const x=adapter();let live;const s=new MemberProcessSupervisor({...x,async start(member,registration){calls.push(registration);live=await x.start(member);return live;}});try{await s.login(a,'first');await live.stop();const [one,two]=await Promise.all([s.login(a,'second'),s.login(a,'third')]);assert.equal(one,two);assert.deepEqual(calls,['first','second']);}finally{await clean(x);}});
